### ISSUE TITLE
Button separators disappear when viewing body for musiclibrary_version_02.txt

### ISSUE THREAD

**Issue by xparadoxical** [SMJSGaming/GDIntercept#3]
![image](https://github.com/SMJSGaming/GDIntercept/assets/43796685/d0f19496-2247-43e6-8318-c2c6c941f19c)

**Comment by SMJSProductions** [comment]
I actually noticed this bug as well, not sure what causes it but it seems to be related to empty code blocks

I'll see if I can find the exact cause

**Comment by SMJSProductions** [comment]
it makes 0 sense to me though, because it should be based on a constant which you can't even get by reference
![image](https://github.com/SMJSGaming/GDIntercept/assets/38814077/51dfd7c3-7c23-47c5-a644-c5f1c988323a)

**Comment by SMJSProductions** [comment]
It seems to get confused on a 0 opacity node. This is most likely an OpenGL bug
https://github.com/SMJSGaming/GDIntercept/assets/38814077/a5213216-d185-4ee1-b82c-d16ba7c64e87
